export const ACTION_TYPES = {
    SET_INPUT_FIELD: 'SET_INPUT_FIELD',
    RESET_FORM: 'RESET_FORM',
    SET_ADD_APPLICATIONS: 'SET_ADD_APPLICATIONS',
    LOAD_APPLICATIONS: 'LOAD_APPLICATIONS',
    DELETE_APPLICATION: 'DELETE_APPLICATION',
    ARCHIVE_APPLICATION: 'ARCHIVE_APPLICATION'
}